const {_electron:electron,expect}=require('@playwright/test');
const assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os');
const {addTestSource}=require('./test-source.cjs');
(async()=>{const temp=await fs.mkdtemp(path.join(os.tmpdir(),'richiflix-focus-'));let app;try{
 app=await electron.launch({executablePath:require('electron'),args:[path.join(__dirname,'main.cjs')],env:{...process.env,RICHIFLIX_TEST_EMPTY_SOURCE:'1',RICHIFLIX_USER_DATA:temp}});
 await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().forEach(win=>win.webContents.setBackgroundThrottling(false)));
 const page=await app.firstWindow(),errors=[];page.on('pageerror',error=>errors.push(error.message));page.on('console',message=>{if(message.text().startsWith('CARD_GEOMETRY'))console.log(message.text());});await page.setViewportSize({width:1920,height:1080});
 await page.addInitScript(()=>{
  localStorage.setItem('rf-profiles',JSON.stringify([{id:'focus',name:'Adulto',kind:'adult'}]));window.__trailers=[];
  window.YT={Player:function(node,options){const iframe=document.createElement('iframe');node.replaceWith(iframe);window.__trailers.push(['created',options.videoId]);let shown=options.videoId;this.getVideoData=()=>({video_id:shown});window.__emitTrailer=(id,state=1)=>{shown=id;options.events.onStateChange({data:state});};window.__trailerError=()=>options.events.onError({data:100});
   this.cueVideoById=id=>{shown=id;window.__trailers.push(['cue',id]);options.events.onStateChange({data:5});};this.pauseVideo=()=>{window.__trailers.push(['pause']);options.events.onStateChange({data:2});};this.getIframe=()=>iframe;this.mute=()=>window.__trailers.push(['mute']);this.unMute=()=>window.__trailers.push(['unmute']);this.setVolume=value=>window.__trailers.push(['volume',value]);this.playVideo=()=>{window.__trailers.push(['play']);options.events.onStateChange({data:1});};this.destroy=()=>{window.__trailers.push(['destroy']);iframe.remove();};
   setTimeout(()=>options.events.onReady({target:this}),20);
  }};
 });await page.reload();await page.getByRole('button',{name:'Adulto',exact:true}).focus();await page.keyboard.press('Enter');
 for(let i=0;i<9;i++)await addTestSource(page,{name:'Título '+i,url:'https://fixture.test/'+i+'.mp4',description:'Sinopsis del título '+i,trailerId:i===1?'TY1lWh20VSw':i===2?'M7lc1UVf-VE':undefined,tmdbId:123+i});
 await page.getByRole('button',{name:'Películas',exact:true}).focus();await page.keyboard.press('Enter');
 const cards=page.locator('.card-open'),stage=page.locator('.focus-stage');const firstSize=await cards.first().evaluate(card=>[card.offsetWidth,card.offsetHeight]);await cards.first().focus();await expect(stage.locator('h1')).toHaveText('Título 0');
 await expect(cards.first().locator('.poster')).toHaveCSS('visibility','visible');await expect(page.locator('.card').first().locator('.card-caption')).toHaveCSS('visibility','visible');await expect(cards.first()).toBeFocused();assert.deepEqual(await cards.first().evaluate(card=>[card.offsetWidth,card.offsetHeight]),firstSize);await expect(page.locator('.card-transfer,.card-banner-position')).toHaveCount(0);
 await page.keyboard.press('ArrowRight');await expect(cards.nth(1)).toBeFocused();await expect(stage.locator('h1')).toHaveText('Título 1');await expect(stage.locator('.focus-description')).toHaveText('Sinopsis del título 1');
 await expect(cards.first().locator('.poster')).toHaveCSS('visibility','visible');await expect(cards.nth(1).locator('.poster')).toHaveCSS('visibility','visible');await expect(page.locator('.card.is-in-banner')).toHaveCount(0);
 await expect(stage.locator('.trailer-preview')).toHaveAttribute('data-trailer-state','playing');await expect(stage.locator('.focus-stage-visual')).toHaveCSS('visibility','hidden');const calls=await page.evaluate(()=>window.__trailers);assert.ok(calls.findIndex(call=>call[0]==='unmute')<calls.findIndex(call=>call[0]==='play'));assert.ok(!calls.some(call=>call[0]==='mute'));await expect(stage.locator('.trailer-preview')).toHaveAttribute('data-trailer-muted','false');
 assert.equal(await stage.locator('.preview-audio').count(),0);await expect(stage.locator('.focus-actions button')).toHaveCount(2);
 await page.keyboard.press('ArrowRight');await expect(cards.nth(2)).toBeFocused();await expect(stage.locator('h1')).toHaveText('Título 2');await expect(stage.locator('.trailer-preview')).toHaveAttribute('data-trailer-state','playing');assert.equal((await page.evaluate(()=>window.__trailers)).filter(call=>call[0]==='created').length,1);assert.ok((await page.evaluate(()=>window.__trailers)).some(call=>call[0]==='cue'&&call[1]==='M7lc1UVf-VE'));
 await page.evaluate(()=>window.__emitTrailer('M7lc1UVf-VE',3));await expect(stage.locator('.focus-stage-visual')).toHaveCSS('visibility','hidden');await page.evaluate(()=>window.__trailerError());await expect(stage.locator('.trailer-preview')).toHaveAttribute('data-trailer-state','poster');await expect(stage.locator('.focus-stage-visual')).toHaveCSS('visibility','visible');await page.evaluate(()=>window.__emitTrailer('M7lc1UVf-VE'));await expect(stage.locator('.focus-stage-visual')).toHaveCSS('visibility','visible');
 await page.evaluate(()=>window.__emitTrailer('TY1lWh20VSw'));await expect(stage.locator('.trailer-preview')).toHaveAttribute('data-trailer-state','poster');
 // A permanent embed error cannot resurrect itself through a late callback.
 // Leaving the section explicitly closes that session before trying again.
 await page.getByRole('button',{name:'Series',exact:true}).click();await expect(stage).toHaveCount(0);
 await page.getByRole('button',{name:'Películas',exact:true}).click();await cards.nth(2).focus();await expect(stage.locator('.trailer-preview')).toHaveAttribute('data-trailer-state','playing');assert.equal(await stage.locator('iframe').count(),1);
 await cards.nth(1).dispatchEvent('mouseenter');await page.waitForTimeout(200);await expect(stage.locator('h1')).toHaveText('Título 2');
 await page.locator('main').dispatchEvent('wheel',{deltaY:40});await expect(page.locator('.app')).toHaveClass(/stage-collapsed/);await expect(stage.locator('.trailer-preview')).toHaveAttribute('data-trailer-state','poster');await expect(stage.locator('.focus-stage-visual')).toHaveCSS('visibility','visible');await expect(page.locator('.app')).not.toHaveClass(/stage-collapsed/);await expect(stage.locator('.trailer-preview')).toHaveAttribute('data-trailer-state','playing');
 await page.keyboard.press('ArrowRight');await expect(stage.locator('h1')).toHaveText('Título 3');await expect(stage.locator('.trailer-preview')).toHaveAttribute('data-trailer-state','poster');assert.equal((await page.evaluate(()=>window.__trailers)).filter(call=>call[0]==='created').length,2);await page.keyboard.press('ArrowLeft');await expect(stage.locator('h1')).toHaveText('Título 2');
 await page.keyboard.press('ArrowUp');await expect(stage.locator('.primary')).toBeFocused();await page.keyboard.press('ArrowDown');await expect(cards.nth(2)).toBeFocused();
 const nextRow=Math.min(8,2+Number(await page.locator('.catalog-grid').getAttribute('data-virtual-columns')));await page.keyboard.press('ArrowDown');await expect(cards.nth(nextRow)).toBeFocused();await expect(page.locator('.app')).toHaveClass(/stage-collapsed/);await page.screenshot({path:path.join(__dirname,'../tv-banner-collapsed.png')});await expect(page.locator('.app')).not.toHaveClass(/stage-collapsed/);await expect(stage.locator('h1')).toHaveText('Título '+nextRow);await page.waitForTimeout(450);assert.ok(await cards.nth(nextRow).evaluate(button=>{const rect=button.closest('.card').getBoundingClientRect(),viewport=button.closest('main').getBoundingClientRect();const ok=rect.top>=viewport.top&&rect.bottom<=viewport.bottom;if(!ok)console.log('CARD_GEOMETRY',JSON.stringify({rect:{top:rect.top,bottom:rect.bottom,height:rect.height},viewport:{top:viewport.top,bottom:viewport.bottom},scroll:button.closest('main').scrollTop,layout:button.closest('.catalog-grid').dataset.virtualColumns}));return ok;}),'Selected card stays visible after banner expands');await page.screenshot({path:path.join(__dirname,'../tv-banner-expanded.png')});const returnIndex=nextRow-Number(await page.locator('.catalog-grid').getAttribute('data-virtual-columns'));await page.keyboard.press('ArrowUp');await expect(cards.nth(returnIndex)).toBeFocused();
 await page.keyboard.press('Escape');await expect(page.getByRole('button',{name:'Películas',exact:true})).toBeFocused();await expect(page.locator('.app')).toHaveClass(/stage-collapsed/);await page.keyboard.press('ArrowDown');await expect(stage.locator('.primary')).toBeFocused();await page.keyboard.press('ArrowDown');await expect(cards.nth(returnIndex)).toBeFocused();
 await expect(stage.locator('h1')).toHaveText('Título '+returnIndex);await page.waitForTimeout(450);await page.screenshot({path:path.join(__dirname,'../tv-focus-preview.png')});await cards.nth(1).hover();const save=page.locator('.card').nth(1).locator('.card-save');await save.click();await expect(save).toHaveAttribute('aria-pressed','true');await save.click();await expect(save).toHaveAttribute('aria-pressed','false');
 await cards.nth(3).hover();await expect(stage.locator('h1')).toHaveText('Título 3');await page.getByRole('button',{name:'Modo TV',exact:true}).click();await cards.nth(3).hover();await expect(page.locator('.pointer-stage h1')).toHaveText('Título 3');await expect(cards.nth(3).locator('.poster')).toHaveCSS('visibility','visible');await page.getByRole('button',{name:'Películas',exact:true}).focus();await page.mouse.move(1,1);await expect(page.locator('.pointer-stage')).toHaveCount(0);await expect(cards.nth(3).locator('.poster')).toHaveCSS('visibility','visible');await expect(page.locator('.card-transfer')).toHaveCount(0);
 await page.getByRole('button',{name:'Modo TV',exact:true}).click();await page.emulateMedia({reducedMotion:'reduce'});await cards.first().focus();await expect(stage.locator('h1')).toHaveText('Título 0');await expect(cards.first().locator('.poster')).toHaveCSS('visibility','visible');await expect(page.locator('.card-transfer')).toHaveCount(0);await expect(cards.first()).toBeFocused();
 const audioCalls=await page.evaluate(()=>window.__trailers);assert.ok(!audioCalls.some(call=>call[0]==='mute'));assert.ok(audioCalls.every((call,index)=>call[0]!=='play'||audioCalls[index-1]?.[0]==='unmute'));assert.equal(await stage.getByRole('button',{name:'Más información',exact:true}).count(),0);assert.deepEqual(errors,[]);console.log('Focus OK: mando por títulos, portada legible, filas, límites, memoria, Volver, hover, banner contraído/expandido, tráiler con sonido por defecto, sin botón de silencio, reutilización, fondo sin imágenes durante el vídeo y restauración al pausar o fallar. Vídeo de prueba simulado.');
}finally{await app?.close();assert.ok(temp.startsWith(os.tmpdir()+path.sep)&&path.basename(temp).startsWith('richiflix-focus-'));await fs.rm(temp,{recursive:true,force:true});}})().catch(error=>{console.error(error);process.exitCode=1;});
